server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/social_platform
    username: admin
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret: mysecretkey
  expiration: 86400000 # 24 hours

# management:
#   endpoints:
#     web:
#       exposure:
#         include: "health"
#   endpoint:
#     health:
#       show-details: always
#   security:
#     enabled: false  # 确保 Actuator 端点不受 Spring Security 保护

management:
  endpoints:
    web:
      exposure:
        include: "*"  # ✅ 允许访问所有 Actuator 端点
  endpoint:
    health:
      show-details: always

